#!/usr/bin/env bash
# Back up the oroginal hosts file
cp /etc/hosts /etc/hosts.new

# change the resolution of facebook.com and localhost
echo "127.0.0.2	localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts.new
